# Generated by Django 2.1.5 on 2019-02-06 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=200)),
                ('site', models.CharField(max_length=3)),
                ('obs_date', models.DateTimeField()),
                ('image', models.FileField(upload_to='%Y/%m/%d/')),
            ],
        ),
    ]
